version: "3"

services:

  uts:
    build:
      context: ./php
    image: "${COMPOSE_PROJECT_NAME}/${REPOSITORY_NAME}_php:${IMAGE_TAG}"
    container_name: "${REPOSITORY_NAME}_php"
    #hostname: "uts"
    volumes:
      - ./src:/var/www/
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/


  uts_nginx:
    build:
      context: ./nginx
    image: "${COMPOSE_PROJECT_NAME}/${REPOSITORY_NAME}_nginx:${IMAGE_TAG}"
    container_name: "${REPOSITORY_NAME}_nginx"
    #hostname: "uts-nginx"
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - uts
      
  dot_db:
    image: mariadb:10.2
    container_name: mysql_dot
    restart: unless-stopped
    tty: true
    ports:
      - "33306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_USER: djambred
      MYSQL_PASSWORD: p455w0rd1!.
      MYSQL_ROOT_PASSWORD: p455w0rd
      TZ: Asia/Jakarta
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql#
